name: Terraform Deploy Prod

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+" # Build for production release with semantic version tag. i.e: v1.1.0 or v2.8.3
      - "!v[0-9]+.[0-9]+.[0-9]+.*" # Not to Build for pre-production release with semantic version tag. i.e: v1.1.1.RC1 or v2.8.4.beta1

  workflow_dispatch:

permissions:
  id-token: write
  contents: read

concurrency: terraform-deploy-prod

jobs:
  lint:
    name: "Lint"
    uses: Um4r-Arafath/tf-test/.github/workflows/lint.yml@main

  terraform-deploy-prod:
    needs: lint
    name: Deploy prod
    uses: Um4r-Arafath/tf-test/.github/workflows/deploy.yml@main
    with:
      aws-region: ap-southeast-1
      role-to-assume: arn:aws:iam::637423543671:role/tf-test
      backend-config: environments/prod/config.s3.tfbackend
      args: -var-file="environments/prod/terraform.tfvars"
      # working-directory: ./services/api/iac
