name: Terraform Deploy Stg

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  terraform-deploy-stg:
    name: Deploy stg
    uses: opstimus/github-actions-terraform/.github/workflows/deploy.yml@main
    with:
      aws-region: ap-southeast-1
      role-to-assume: arn:aws:iam::637423543671:role/github-actions-role
      backend-config: environments/stg/config.s3.tfbackend
      args: -var-file="environments/stg/terraform.tfvars"
      working-directory: ./services/api/iac
      deploy: true
