name: Terraform CI

on:
  push:
    branches:
      - main
      - "release/v**"

  pull_request:
    branches:
      - main
      - "release/v**"

jobs:
  lint:
    name: "Lint"
    uses: Um4r-Arafath/tf-test/.github/workflows/lint.yml@main
